GET http://localhost:3001/api/tasks

###
POST http://localhost:3001/api/tasks/
content-type: application/json

{
  "content": "Investigate the WebStorm REST client further",
  "important": false
}

###
GET http://localhost:3001/api/tasks/someInvalidId

###
POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "root",
  "name": "Test User",
  "password": "tigers"
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "pacrock",
  "name": "Khoury Graffiti Rock",
  "password": "ilikepaint"
}

###
POST http://localhost:3001/api/tasks
content-type: application/json

{
  "content": "Stay put",
  "important": "true",
  "userId": "63c9bcc35a769983693bd0ca"
}

###
POST http://localhost:3001/api/tasks
content-type: application/json

{
  "content": "Get a paint job",
  "important": "true",
  "userId": "63c9bcc35a769983693bd0ca"
}